import designStyles from '@antfu/design/styles.css?inline'
import { defineCustomElement } from 'vue'
import vueAfloatStyles from 'vue-afloat/style.css?inline'
import mainCss from '../assets/css/main.css?inline'
import EmbedApp from './EmbedApp.ce.vue'
// Generated by `pnpm run build:embed:uno` (see package.json) - `virtual:uno.css?inline`
// doesn't resolve under this single-chunk build (an internal UnoCSS/Rolldown
// resolution bug with `inlineDynamicImports`), so this is a real file scanned ahead of
// time via the `unocss` CLI against the same `uno.config.ts` instead.
import unoCss from './uno-generated.css?inline'

// Shadow DOM is isolated from github.com's page stylesheets entirely - push the same
// global CSS `app/main.ts` imports for the main site into this component's own
// `styles` (populated by `@vitejs/plugin-vue`'s `.ce.vue` compiler mode), so it lands
// inside the shadow root instead.
EmbedApp.styles ??= []
EmbedApp.styles.push(designStyles, vueAfloatStyles, mainCss, unoCss)

customElements.define('diffs-embed-panel', defineCustomElement(EmbedApp))
